LaserCuttingAndEngravingServices/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using LaserCuttingAndEngravingServices.Helpers;

namespace LaserCuttingAndEngravingServices.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendMessage(string name, string surname, string userEmail, string need, string message)
        {           
            if (ModelState.IsValid)
            {
                string body = "Need: " + need + "\n" +
                    "Email: " + userEmail + "\n" +
                    message;

                if (EmailEx.Send(name + " " + surname, userEmail, "Contact Page Inquiry", body))
                {
                    return View("SendMessage", "The following message was sent successfully: \n" + message);
                }
                else
                {
                    return View("SendMessage", "We were unable to send your message due to internal errors.");
                }
                  
            }
            else
            {
                return View("SendMessage", "We were unable to send your message due to input validation errors.");
            }          
        }
    }
}

LaserCuttingAndEngravingServices/Controllers/CustomJobsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using LaserCuttingAndEngravingServices.Helpers;

namespace LaserCuttingAndEngravingServices.Controllers
{
    public class CustomJobsController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        public CustomJobsController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }


        // GET: CustomJobs
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost("FileUpload")]
        public async Task<IActionResult> FileUpload(List<IFormFile> files,  string jobDescription, string lastName, string firstName, string userEmail)
        {
            string webRootPath = _hostingEnvironment.WebRootPath;
            string contentRootPath = _hostingEnvironment.ContentRootPath;

            long size = files.Sum(f => f.Length);

            var filePaths = new List<string>();
            var fileNames = new StringBuilder();
            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    // full path to file in temp location
                    var fileName = Path.GetFileName(formFile.FileName);
                    var filePath = Path.Combine(contentRootPath,"Uploads", fileName);// Path.GetTempFileName();
                    fileNames.Append(fileName);
                    filePaths.Add(filePath);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            var sendResult = string.Empty;
            var body = jobDescription + "\n" + "Files: " + fileNames.ToString();
            if (EmailEx.Send(lastName + "," + firstName, userEmail, "Job Request", body))
            {
                ViewBag.Status = "Your job request was successfully sent!";
                sendResult = "Customer: " + lastName + "," + firstName + "\n";
                sendResult += "Email: " + userEmail + "\n";
                sendResult += "File Count: " + files.Count + "\n";
                sendResult += "Size: " + size + "\n";
                sendResult += "Files: " + fileNames.ToString();
            }
            else
            {
                ViewBag.Status = "Your job request was not successfully sent";
            }

            return View("FileUpload", sendResult);
            // process uploaded files
            // Don't rely on or trust the FileName property without validation.

            //return Ok(new { count = files.Count, size, filePaths });
        }

        // GET: CustomJobs/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CustomJobs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomJobs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomJobs/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CustomJobs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomJobs/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CustomJobs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LaserCuttingAndEngravingServices/Controllers/PanelTagsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;

namespace LaserCuttingAndEngravingServices.Controllers
{
    public class PanelTagsController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        public PanelTagsController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        // GET: PanelTags
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadSVG()
        {
            string contentRootPath = _hostingEnvironment.ContentRootPath;

            var file = Request.Form.Files[0];
           
            if (file != null)
            {
                var dt = DateTime.Now;
                var fileName = "SVGUpload_" + String.Format("{0:d_M_yyyy_HH.mm.ss.fff}" + ".svg", dt);
                var filePath = Path.Combine(contentRootPath, "UploadSvgs", fileName);
               
                try
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    return Json(fileName);
                }
                catch (Exception ex)
                {
                    return Json(ex.Message);
                }
            }
            return Json("No data uploaded!");

        }

        // GET: PanelTags/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PanelTags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PanelTags/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PanelTags/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PanelTags/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PanelTags/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PanelTags/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LaserCuttingAndEngravingServices/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Luceva Services</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container" id="dvMainContainer">
        <header>
            <div class="container" id="dvHeaderContainer">
                <div class="row">
                    <div class="col-2.5">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="~/img/LogoBlue.png" width="100" height="100" />
                        </a>
                    </div>
                    <div class="col-8">
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        <h1 style="font-family: Britannic; font-weight: bold; font-size: 40px; align-content:center">
                            Laser Cutting and Engraving Services
                        </h1>
                    </div>
                </div>
            </div>
            <nav id="navTop" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="PanelTags" asp-action="Index">Industrial Panel Tags</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="RubberStamps" asp-action="Index">Rubber Stamps</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="CustomJobs" asp-action="Index">Custom Jobs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Contact" asp-action="Index">Contact us</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main id="main" role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer id="footer" class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - Luceva Services - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script>
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })
        </script>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>